apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: busybox
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/*

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: run-nose-tests
      image: python:3.11
      script: |
        #!/bin/sh
        echo "Installing nose..."
        pip install --no-cache-dir nose
        echo "Running nose tests..."
        nosetests


