name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install flake8 nose

      - name: Run linter
        run: |
          flake8 .

      - name: Run unit tests with nose
        run: |
          nosetests

